WAFT:
  FEATURE_ENCODER:
    TYPE: "mnv4"
    ARCH: "mobilenetv4_conv_large"
    LORA_RANK: 8
    LORA_ALPHA: 16
  ITERATIVE_MODULE:
    TASK: ['delta', 'delta', 'delta', 'delta']
    PROP_ITER:
      TYPE: "mnv4"
      HIDDEN_DIM: 192
      NUM_UIB_BLOCKS: 6
      RES_LAYERS: 6
    DELTA_ITER:
      TYPE: "mnv4"
      HIDDEN_DIM: 192
      NUM_UIB_BLOCKS: 6
      RES_LAYERS: 6
  MAX_DISP: 800
  LOSS: ['mixlap_40']

DATASETS:
  TRAIN: ("sanpo_real_train",)
  MUL: (1,)
  CROP_SIZE: [320, 240]
  TEST: ("sanpo_real_val",)

SOLVER:
  RESUME: "checkpoints/stage1-tartan-large/checkpoint_best.pth"
  BASE_LR: 5.0e-5
  IMS_PER_BATCH: 4
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
